export type CapabilityStatus = "LIVE" | "PARTIALLY_CONNECTED" | "NOT_CONNECTED" | "FAILED";

export type CapabilityCategory =
  | "sales"
  | "customers"
  | "team"
  | "communication"
  | "finance"
  | "ai";

export interface CapabilityAudit {
  frontendExists: boolean;
  serverFnExists: boolean;
  backendServiceExists: boolean;
  dbOperationExists: boolean;
  externalProviderRequired: boolean;
  providerConfigured: boolean;
  realExecutionImplemented: boolean;
  executionResultRecorded: boolean;
  failureHandlingImplemented: boolean;
  endToEndTested: boolean;
}

export interface CapabilityStep {
  step: number;
  title: string;
  description: string;
  tool: string;
}

export interface CapabilityDefinition {
  id: string;
  name: string;
  category: CapabilityCategory;
  description: string;
  status: CapabilityStatus;
  statusDetails: string;
  audit: CapabilityAudit;
  steps: CapabilityStep[];
  defaultSchedule: string;
  defaultTrigger: string;
  assignmentSupported: boolean;
  defaultAssignmentStrategy: "round_robin" | "lowest_workload" | "skill_based" | "direct" | "ai_assignment";
  targetType: "lead" | "customer" | "team_member" | "invoice" | "report" | "general";
  missingComponent?: string;
  providerRecommendation?: string;
}

export const CAPABILITIES_CATALOG: CapabilityDefinition[] = [
  // ── SALES ──────────────────────────────────────────────────────────────────
  {
    id: "sales_lead_qualification",
    name: "Lead Qualification",
    category: "sales",
    description: "Evaluates inbound lead information, budget signals, company fit, and calculates lead quality score (0-100).",
    status: "LIVE",
    statusDetails: "AI heuristic & Gemini evaluation actively calculates score and updates Supabase leads table.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Ingest Lead Record", description: "Collect lead email, company, and source channel from CRM.", tool: "fetch_lead" },
      { step: 2, title: "Analyze Fit & Intent", description: "Evaluate ICP compatibility, email domain, and deal estimate.", tool: "ai_score_lead" },
      { step: 3, title: "Assign Score & Stage", description: "Update lead stage to 'qualified' or 'unqualified' in database.", tool: "update_lead_db" },
      { step: 4, title: "Log Audit Trail", description: "Record scoring breakdown in activity stream.", tool: "log_execution" },
    ],
    defaultSchedule: "Triggered on new lead creation",
    defaultTrigger: "new_lead",
    assignmentSupported: true,
    defaultAssignmentStrategy: "round_robin",
    targetType: "lead",
  },
  {
    id: "sales_lead_assignment",
    name: "Lead Assignment",
    category: "sales",
    description: "Distributes qualified leads to sales team members using Round Robin, Lowest Workload, or Skill-matching strategies.",
    status: "LIVE",
    statusDetails: "Intelligent routing engine resolves active work groups and updates lead owner in Supabase.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Identify Unassigned Leads", description: "Query leads table where owner_id is unassigned.", tool: "query_unassigned_leads" },
      { step: 2, title: "Resolve Target Work Group", description: "Match lead criteria to Sales or Enterprise Sales work group.", tool: "resolve_work_group" },
      { step: 3, title: "Execute Assignment Strategy", description: "Apply selected routing strategy (Round Robin / Lowest Workload).", tool: "execute_routing_algorithm" },
      { step: 4, title: "Update Lead Owner & Notify", description: "Write owner_id to lead and create in-app notification for rep.", tool: "assign_lead_owner" },
    ],
    defaultSchedule: "Triggered immediately on lead creation",
    defaultTrigger: "new_lead",
    assignmentSupported: true,
    defaultAssignmentStrategy: "round_robin",
    targetType: "lead",
  },
  {
    id: "sales_follow_up",
    name: "Follow-up Creation",
    category: "sales",
    description: "Automatically schedules follow-up tasks and outreach agendas for stale leads or post-discovery deals.",
    status: "LIVE",
    statusDetails: "Generates unified work items (tasks) in database with AI talking points and assigned rep.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Audit Pipeline Activity", description: "Identify leads with no recorded touchpoint in >48 hours.", tool: "scan_lead_activity" },
      { step: 2, title: "Synthesize Outreach Context", description: "AI compiles customer background and suggested agenda.", tool: "ai_draft_outreach" },
      { step: 3, title: "Create Follow-up Work Item", description: "Insert scheduled follow-up task in Supabase tasks table.", tool: "insert_task" },
      { step: 4, title: "Alert Assigned Representative", description: "Push work item to assignee's pending work queue.", tool: "push_notification" },
    ],
    defaultSchedule: "Daily audit at 9:30 AM",
    defaultTrigger: "schedule_cron",
    assignmentSupported: true,
    defaultAssignmentStrategy: "lowest_workload",
    targetType: "lead",
  },
  {
    id: "sales_reporting",
    name: "Sales Reporting",
    category: "sales",
    description: "Aggregates pipeline velocity, active opportunities, deal stages, and win rates into sales intelligence reports.",
    status: "LIVE",
    statusDetails: "Calculates real-time deal stage totals, pipeline value, and conversion velocity from database.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Query Deals & Pipeline", description: "Fetch all active deals, values, and stage transitions.", tool: "fetch_deals" },
      { step: 2, title: "Calculate Velocity & Win Rate", description: "Compute average cycle time and win/loss ratio.", tool: "calculate_metrics" },
      { step: 3, title: "Synthesize Sales Summary", description: "Generate formatted pipeline briefing with top revenue opportunities.", tool: "compile_sales_brief" },
      { step: 4, title: "Publish Briefing to Workspace", description: "Record report snapshot in system analytics.", tool: "save_report_snapshot" },
    ],
    defaultSchedule: "Every weekday at 5:00 PM",
    defaultTrigger: "schedule_cron",
    assignmentSupported: true,
    defaultAssignmentStrategy: "direct",
    targetType: "report",
  },

  // ── CUSTOMERS ──────────────────────────────────────────────────────────────
  {
    id: "customers_routing",
    name: "Customer Routing",
    category: "customers",
    description: "Routes new and existing customers to dedicated account managers or customer success tiers.",
    status: "LIVE",
    statusDetails: "Evaluates customer segments and assigns account ownership to customer success work groups.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Detect Customer Event", description: "Trigger on new signup, upgrade, or segment change.", tool: "customer_event_listener" },
      { step: 2, title: "Evaluate Segment Rules", description: "Match customer revenue/tier to Customer Success Group.", tool: "match_segment" },
      { step: 3, title: "Assign Success Specialist", description: "Select representative based on workload or tier specialization.", tool: "assign_specialist" },
      { step: 4, title: "Create Onboarding Work Item", description: "Create customer onboarding checklist task.", tool: "create_onboarding_task" },
    ],
    defaultSchedule: "Triggered on customer creation / upgrade",
    defaultTrigger: "new_customer",
    assignmentSupported: true,
    defaultAssignmentStrategy: "skill_based",
    targetType: "customer",
  },
  {
    id: "customers_groups",
    name: "Customer Groups Routing",
    category: "customers",
    description: "Dynamically manages customer segmentation (VIP, At-Risk, Enterprise, Free Tier) with automated membership rules.",
    status: "LIVE",
    statusDetails: "Directly queries and synchronizes customer_groups and customer_group_members in database.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Audit Customer Cohorts", description: "Filter customer database by status, activity, and spend.", tool: "scan_customers" },
      { step: 2, title: "Update Segment Membership", description: "Sync customer_group_members table in Supabase.", tool: "sync_group_members" },
      { step: 3, title: "Trigger Cohort Actions", description: "Initiate cohort-specific nurturing or risk escalation workflows.", tool: "dispatch_cohort_actions" },
    ],
    defaultSchedule: "Daily audit at midnight",
    defaultTrigger: "schedule_cron",
    assignmentSupported: false,
    defaultAssignmentStrategy: "direct",
    targetType: "customer",
  },
  {
    id: "customers_follow_up",
    name: "Customer Follow-up",
    category: "customers",
    description: "Detects inactive or at-risk accounts and dispatches proactive retention tasks to Customer Success reps.",
    status: "LIVE",
    statusDetails: "Scans for inactivity >14 days and creates targeted check-in tasks in Supabase tasks table.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Detect Account Inactivity", description: "Query customer accounts with 0 touchpoints in >14 days.", tool: "scan_inactive_accounts" },
      { step: 2, title: "Calculate Churn Urgency", description: "AI evaluates engagement history and renewal timeline.", tool: "ai_evaluate_churn_risk" },
      { step: 3, title: "Assign CS Specialist", description: "Assign account retention task to CS Work Group.", tool: "assign_cs_task" },
      { step: 4, title: "Generate Value Agenda", description: "AI drafts suggested check-in talking points.", tool: "ai_talking_points" },
    ],
    defaultSchedule: "Weekly audit every Monday at 9:00 AM",
    defaultTrigger: "schedule_cron",
    assignmentSupported: true,
    defaultAssignmentStrategy: "lowest_workload",
    targetType: "customer",
  },

  // ── TEAM ───────────────────────────────────────────────────────────────────
  {
    id: "team_assign_individual",
    name: "Assign to Individual",
    category: "team",
    description: "Directly routes specific business work items, reviews, or escalations to a chosen employee.",
    status: "LIVE",
    statusDetails: "Assigns assignee_id directly to selected organization member and logs notification.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Validate Member Status", description: "Verify targeted team member is active in workspace.", tool: "validate_member" },
      { step: 2, title: "Attach Work Payload", description: "Bind task description, priority, customer, and due date.", tool: "bind_task_data" },
      { step: 3, title: "Persist Task Assignment", description: "Write task to database with explicit assignee_id.", tool: "insert_task_db" },
      { step: 4, title: "Deliver Direct Notification", description: "Push in-app alert to employee's workspace feed.", tool: "send_in_app_alert" },
    ],
    defaultSchedule: "Event-triggered or manual run",
    defaultTrigger: "manual_or_event",
    assignmentSupported: true,
    defaultAssignmentStrategy: "direct",
    targetType: "team_member",
  },
  {
    id: "team_assign_work_group",
    name: "Assign to Work Group",
    category: "team",
    description: "Routes work items to dedicated employee teams (Sales, CS, Finance, Operations) using intelligent load distribution.",
    status: "LIVE",
    statusDetails: "Queries work_group_members, applies group assignment strategy, and logs work item.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Resolve Target Work Group", description: "Fetch eligible members for selected work group ID.", tool: "fetch_group_members" },
      { step: 2, title: "Apply Group Strategy", description: "Execute Round Robin / Workload Optimizer across group pool.", tool: "apply_group_strategy" },
      { step: 3, title: "Assign Selected Member", description: "Assign task to chosen member with work_group_id tag.", tool: "create_group_task" },
      { step: 4, title: "Update Group Workload KPIs", description: "Recalculate active task count for group dashboard.", tool: "update_group_kpis" },
    ],
    defaultSchedule: "Event-triggered on incoming business demand",
    defaultTrigger: "custom_event",
    assignmentSupported: true,
    defaultAssignmentStrategy: "round_robin",
    targetType: "team_member",
  },
  {
    id: "team_assign_multiple",
    name: "Multiple-Member Assignment",
    category: "team",
    description: "Broadcasts multi-part work or distributes parallel checklists across all members in a functional unit.",
    status: "LIVE",
    statusDetails: "Fans out coordinated tasks across all active members of the target work group.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Query Member Roster", description: "Fetch all active members in target group.", tool: "fetch_roster" },
      { step: 2, title: "Generate Parallel Work Items", description: "Create individual task records for each team member.", tool: "batch_create_tasks" },
      { step: 3, title: "Broadcast Team Notification", description: "Notify all recipients with assignment context.", tool: "batch_notify" },
    ],
    defaultSchedule: "Event-triggered or manual trigger",
    defaultTrigger: "manual_or_event",
    assignmentSupported: true,
    defaultAssignmentStrategy: "direct",
    targetType: "team_member",
  },
  {
    id: "team_round_robin",
    name: "Round Robin Assignment",
    category: "team",
    description: "Rotates incoming work items sequentially across team members to guarantee perfectly fair distribution.",
    status: "LIVE",
    statusDetails: "Maintains atomic pointer rotation scoped per organization and work group.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Query Available Pool", description: "Fetch available members not marked 'offline' or 'on_leave'.", tool: "fetch_available_pool" },
      { step: 2, title: "Advance Pointer", description: "Calculate (last_index + 1) % pool.length.", tool: "advance_pointer" },
      { step: 3, title: "Assign Chosen Rep", description: "Assign task/lead to selected rep with rotation step logged.", tool: "assign_task" },
      { step: 4, title: "Save Pointer State", description: "Update in-memory and database rotation tracker.", tool: "save_pointer" },
    ],
    defaultSchedule: "Executed in real time on routing events",
    defaultTrigger: "routing_event",
    assignmentSupported: true,
    defaultAssignmentStrategy: "round_robin",
    targetType: "team_member",
  },
  {
    id: "team_workload_balancing",
    name: "Workload Balancing",
    category: "team",
    description: "Dynamically audits active non-completed tasks per member and routes new work to the team member with the lowest load.",
    status: "LIVE",
    statusDetails: "Queries active task counts from tasks table and assigns to least-loaded candidate in real time.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Audit Active Tasks", description: "Query non-completed tasks grouped by assignee_id.", tool: "query_active_task_counts" },
      { step: 2, title: "Rank Candidates", description: "Sort eligible members ascending by current task volume.", tool: "rank_by_workload" },
      { step: 3, title: "Dispatch to Least Loaded", description: "Assign new task to member with lowest count.", tool: "assign_task" },
      { step: 4, title: "Record Load Metrics", description: "Log pre- and post-assignment workload in execution trace.", tool: "log_workload_trace" },
    ],
    defaultSchedule: "Executed in real time on routing events",
    defaultTrigger: "routing_event",
    assignmentSupported: true,
    defaultAssignmentStrategy: "lowest_workload",
    targetType: "team_member",
  },
  {
    id: "team_reassign",
    name: "Reassign Work",
    category: "team",
    description: "Reassigns overdue or escalated tasks from overloaded employees to available teammates.",
    status: "LIVE",
    statusDetails: "Updates assignee_id on tasks table and generates reassignment audit log.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Identify Target Work Item", description: "Fetch task details and verify current status.", tool: "fetch_task" },
      { step: 2, title: "Select New Assignee", description: "Apply workload optimizer or manual member selection.", tool: "resolve_new_assignee" },
      { step: 3, title: "Update Task Assignee", description: "Modify assignee_id and timestamp in database.", tool: "update_task_assignee" },
      { step: 4, title: "Notify Both Parties", description: "Send notification to previous and newly assigned reps.", tool: "notify_reassignment" },
    ],
    defaultSchedule: "Event-triggered or manual reassignment",
    defaultTrigger: "manual_or_event",
    assignmentSupported: true,
    defaultAssignmentStrategy: "lowest_workload",
    targetType: "team_member",
  },

  // ── COMMUNICATION ──────────────────────────────────────────────────────────
  {
    id: "comm_daily_reports",
    name: "Daily Business Report",
    category: "communication",
    description: "Aggregates revenue, pipeline, customer health, and pending tasks into an executive intelligence brief.",
    status: "LIVE",
    statusDetails: "Live database metric synthesis & in-app briefing drawer is LIVE. External email delivery is PARTIAL (requires SMTP/Resend).",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: true,
      providerConfigured: false,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Collect Real Business Data", description: "Query live revenue, active pipeline, customer counts, and urgent tasks.", tool: "query_database_metrics" },
      { step: 2, title: "Analyze Performance", description: "Synthesize cash flow alerts, pipeline velocity, and operational priorities.", tool: "ai_synthesize_brief" },
      { step: 3, title: "Generate Executive Report", description: "Compile structured executive briefing with key highlights.", tool: "compile_executive_report" },
      { step: 4, title: "Deliver In-App & Check Email", description: "Publish in-app briefing; verify if SMTP/Resend is configured for email dispatch.", tool: "deliver_briefing" },
      { step: 5, title: "Record Execution Log", description: "Save execution status, duration, and metrics to audit log.", tool: "log_execution" },
    ],
    defaultSchedule: "Every weekday at 9:00 AM",
    defaultTrigger: "schedule_cron",
    assignmentSupported: true,
    defaultAssignmentStrategy: "direct",
    targetType: "report",
    missingComponent: "External Email Transport (SMTP / Resend)",
    providerRecommendation: "Add RESEND_API_KEY or SMTP_URL in .env to enable direct email inbox delivery. In-app executive briefings and clipboard exports work fully.",
  },
  {
    id: "comm_send_email",
    name: "Send Email",
    category: "communication",
    description: "Dispatches transactional emails, reports, customer onboarding letters, and payment notices.",
    status: "PARTIALLY_CONNECTED",
    statusDetails: "Template drafting and data formatting works. Real SMTP/Resend transport is not yet configured in environment.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: true,
      providerConfigured: false,
      realExecutionImplemented: false,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: false,
    },
    steps: [
      { step: 1, title: "Draft Email Payload", description: "Populate email subject, recipient, and HTML/markdown template.", tool: "render_template" },
      { step: 2, title: "Check Transport Provider", description: "Verify RESEND_API_KEY, SENDGRID_API_KEY, or SMTP credentials in .env.", tool: "check_email_provider" },
      { step: 3, title: "Dispatch to Mail Server", description: "Transmit payload via provider SDK or SMTP transport.", tool: "transport_send" },
      { step: 4, title: "Record Delivery Status", description: "Log message ID or transparent provider-missing warning.", tool: "log_email_result" },
    ],
    defaultSchedule: "Event-triggered on customer/invoice action",
    defaultTrigger: "custom_event",
    assignmentSupported: false,
    defaultAssignmentStrategy: "direct",
    targetType: "general",
    missingComponent: "Email Service Provider (Resend / SendGrid / SMTP)",
    providerRecommendation: "Configure RESEND_API_KEY in .env. Execution currently captures data and logs delivery warning transparently without fake success.",
  },
  {
    id: "comm_manager_notifications",
    name: "Manager Notifications",
    category: "communication",
    description: "Broadcasts critical business alerts (large deal won, high-value invoice overdue, capacity warning) to management.",
    status: "LIVE",
    statusDetails: "Writes directly to notifications table in Supabase and renders in workspace notification drawer.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Evaluate Escalation Threshold", description: "Check if event exceeds high-value threshold (e.g. Deal > $10,000).", tool: "evaluate_threshold" },
      { step: 2, title: "Resolve Management Recipients", description: "Query organization admins and managers.", tool: "query_managers" },
      { step: 3, title: "Insert In-App Notifications", description: "Batch write notification records into Supabase.", tool: "insert_notifications" },
      { step: 4, title: "Log Escalation Event", description: "Record escalation in live activity audit trail.", tool: "log_escalation" },
    ],
    defaultSchedule: "Triggered on critical business events",
    defaultTrigger: "critical_event",
    assignmentSupported: true,
    defaultAssignmentStrategy: "direct",
    targetType: "team_member",
  },
  {
    id: "comm_customer_notifications",
    name: "Customer Notifications",
    category: "communication",
    description: "Sends automated customer confirmation notices, order updates, and renewal reminders.",
    status: "LIVE",
    statusDetails: "In-app activity logging is LIVE; external push/SMS requires external provider configuration.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Format Notification Content", description: "Assemble customer personalized update text.", tool: "format_message" },
      { step: 2, title: "Record Activity Log", description: "Log touchpoint in customer timeline.", tool: "insert_activity" },
      { step: 3, title: "Schedule Next Touchpoint", description: "Create follow-up task if customer response needed.", tool: "schedule_touchpoint" },
    ],
    defaultSchedule: "Triggered on customer status change",
    defaultTrigger: "customer_status_change",
    assignmentSupported: true,
    defaultAssignmentStrategy: "skill_based",
    targetType: "customer",
  },
  {
    id: "comm_whatsapp",
    name: "WhatsApp Notifications",
    category: "communication",
    description: "Automates instant customer messaging via WhatsApp Business API for order receipts and reminders.",
    status: "NOT_CONNECTED",
    statusDetails: "No WhatsApp Business Cloud API or Twilio WhatsApp credentials configured in environment.",
    audit: {
      frontendExists: true,
      serverFnExists: false,
      backendServiceExists: false,
      dbOperationExists: false,
      externalProviderRequired: true,
      providerConfigured: false,
      realExecutionImplemented: false,
      executionResultRecorded: false,
      failureHandlingImplemented: false,
      endToEndTested: false,
    },
    steps: [
      { step: 1, title: "Resolve Customer Phone", description: "Query customer verified E.164 phone number.", tool: "fetch_phone" },
      { step: 2, title: "Format Template Message", description: "Select approved Meta WhatsApp message template.", tool: "format_whatsapp_template" },
      { step: 3, title: "Transmit via Meta API", description: "Send HTTP POST to Meta WhatsApp Cloud API endpoint.", tool: "whatsapp_cloud_api" },
      { step: 4, title: "Capture Delivery Receipt", description: "Track message sent, delivered, and read status.", tool: "log_receipt" },
    ],
    defaultSchedule: "Event-triggered on instant alerts",
    defaultTrigger: "instant_alert",
    assignmentSupported: false,
    defaultAssignmentStrategy: "direct",
    targetType: "customer",
    missingComponent: "Meta WhatsApp Cloud API / Twilio WhatsApp Credentials",
    providerRecommendation: "Configure WHATSAPP_API_TOKEN and WHATSAPP_PHONE_NUMBER_ID in .env or connect via Integrations page.",
  },

  // ── FINANCE ────────────────────────────────────────────────────────────────
  {
    id: "finance_invoice_actions",
    name: "Invoice Actions",
    category: "finance",
    description: "Monitors invoice lifecycle (draft, sent, paid, overdue) and coordinates payment reminders.",
    status: "LIVE",
    statusDetails: "Full CRUD and status transitions verified in Supabase invoices table.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Scan Overdue Invoices", description: "Filter invoices where status = 'sent' and due_date < today.", tool: "query_overdue_invoices" },
      { step: 2, title: "Calculate Outstanding Aging", description: "Compute days overdue and interest penalty if applicable.", tool: "calculate_aging" },
      { step: 3, title: "Update Invoice Status", description: "Set status to 'overdue' in Supabase.", tool: "update_invoice_status" },
      { step: 4, title: "Create Finance Work Item", description: "Assign collection task to Finance Work Group.", tool: "create_collection_task" },
    ],
    defaultSchedule: "Daily audit at 8:00 AM",
    defaultTrigger: "schedule_cron",
    assignmentSupported: true,
    defaultAssignmentStrategy: "lowest_workload",
    targetType: "invoice",
  },
  {
    id: "finance_payment_followup",
    name: "Payment Follow-up",
    category: "finance",
    description: "Automates courteous payment reminders and assigns recovery tasks for unpaid customer accounts.",
    status: "LIVE",
    statusDetails: "Generates tailored collection work items in database with invoice follow-up actions.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Audit Unpaid Balances", description: "Query accounts with outstanding balances >0.", tool: "query_unpaid_balances" },
      { step: 2, title: "Draft Payment Notice", description: "AI generates personalized payment reminder with payment link.", tool: "ai_draft_reminder" },
      { step: 3, title: "Route to Finance Specialist", description: "Assign follow-up task to Finance Work Group via Lowest Workload.", tool: "assign_finance_task" },
      { step: 4, title: "Monitor Settlement", description: "Auto-complete task when invoice is marked as paid.", tool: "monitor_settlement" },
    ],
    defaultSchedule: "Daily audit at 9:00 AM",
    defaultTrigger: "schedule_cron",
    assignmentSupported: true,
    defaultAssignmentStrategy: "lowest_workload",
    targetType: "invoice",
  },
  {
    id: "finance_financial_reports",
    name: "Financial Reports",
    category: "finance",
    description: "Calculates settled revenue, accounts receivable, overdue debt, and cash-flow health metrics.",
    status: "LIVE",
    statusDetails: "Live aggregation across invoices and payments tables with currency formatting.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Aggregate Invoiced Totals", description: "Sum paid, sent, and overdue invoice amounts.", tool: "aggregate_revenue" },
      { step: 2, title: "Compute Collection Rate", description: "Calculate settled revenue vs. total invoiced.", tool: "calculate_collection_rate" },
      { step: 3, title: "Synthesize Cash Flow Brief", description: "Generate formatted financial brief with cash flow alerts.", tool: "compile_finance_brief" },
      { step: 4, title: "Log Financial Summary", description: "Save snapshot to workspace analytics.", tool: "save_analytics_snapshot" },
    ],
    defaultSchedule: "Every Monday at 8:30 AM",
    defaultTrigger: "schedule_cron",
    assignmentSupported: true,
    defaultAssignmentStrategy: "direct",
    targetType: "report",
  },

  // ── AI ─────────────────────────────────────────────────────────────────────
  {
    id: "ai_analysis",
    name: "AI Analysis",
    category: "ai",
    description: "Deeply analyzes business operations, customer risk factors, deal bottlenecks, and revenue anomalies.",
    status: "LIVE",
    statusDetails: "Powered by Gemini 1.5 Flash API with deterministic heuristic fallback.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: true,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Collect Workspace Data", description: "Aggregate recent activity, task completion rates, and CRM signals.", tool: "collect_context" },
      { step: 2, title: "Execute Gemini Reasoning", description: "Process context via Gemini API to identify bottlenecks and trends.", tool: "gemini_reasoning" },
      { step: 3, title: "Structure Strategic Findings", description: "Format insights into actionable recommendations.", tool: "structure_insights" },
      { step: 4, title: "Publish Recommendations", description: "Display insights in Autopilot command center feed.", tool: "publish_insights" },
    ],
    defaultSchedule: "Continuous background analysis & daily digest",
    defaultTrigger: "continuous_or_cron",
    assignmentSupported: false,
    defaultAssignmentStrategy: "ai_assignment",
    targetType: "general",
  },
  {
    id: "ai_assignment",
    name: "AI Assignment Dispatcher",
    category: "ai",
    description: "Uses AI reasoning to evaluate team workload, member skills, and availability to select the ideal assignee.",
    status: "LIVE",
    statusDetails: "Evaluates candidate skills, current load, and historical completion metrics.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Analyze Work Complexity", description: "Assess required skill tags and urgency of work item.", tool: "analyze_work_item" },
      { step: 2, title: "Evaluate Team Roster", description: "Match requirements against member skills and active capacity.", tool: "evaluate_roster" },
      { step: 3, title: "Select Optimal Assignee", description: "Pick best suited team member with reasoning explanation.", tool: "select_best_match" },
      { step: 4, title: "Dispatch Work & Log Reason", description: "Create task and write AI decision reasoning to audit log.", tool: "dispatch_and_log" },
    ],
    defaultSchedule: "Triggered on intelligent routing events",
    defaultTrigger: "routing_event",
    assignmentSupported: true,
    defaultAssignmentStrategy: "ai_assignment",
    targetType: "team_member",
  },
  {
    id: "ai_reports",
    name: "AI Intelligence Reports",
    category: "ai",
    description: "Autonomous generation of multi-department synthesis reports combining Sales, CS, and Finance.",
    status: "LIVE",
    statusDetails: "Synthesizes multi-table metrics into clear markdown briefings with executive talking points.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: true,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Cross-Department Scan", description: "Query pipeline, collections, and team productivity.", tool: "scan_cross_department" },
      { step: 2, title: "Synthesize Executive Notes", description: "AI detects anomalies, top performers, and cash flow alerts.", tool: "ai_synthesize" },
      { step: 3, title: "Compile Document", description: "Format brief with tables, KPI comparisons, and action items.", tool: "compile_document" },
      { step: 4, title: "Distribute to Workspace", description: "Make available in Executive Briefing modal.", tool: "distribute_briefing" },
    ],
    defaultSchedule: "Every weekday morning",
    defaultTrigger: "schedule_cron",
    assignmentSupported: true,
    defaultAssignmentStrategy: "direct",
    targetType: "report",
  },
  {
    id: "ai_recommendations",
    name: "AI Recommendations",
    category: "ai",
    description: "Proactively suggests high-impact Autopilots based on real business friction detected in the database.",
    status: "LIVE",
    statusDetails: "Scans for unassigned leads, overdue invoices, and idle deals to generate one-click solutions.",
    audit: {
      frontendExists: true,
      serverFnExists: true,
      backendServiceExists: true,
      dbOperationExists: true,
      externalProviderRequired: false,
      providerConfigured: true,
      realExecutionImplemented: true,
      executionResultRecorded: true,
      failureHandlingImplemented: true,
      endToEndTested: true,
    },
    steps: [
      { step: 1, title: "Friction Audit", description: "Scan database for unassigned leads, overdue invoices, and bottleneck tasks.", tool: "scan_friction" },
      { step: 2, title: "Generate Actionable Solutions", description: "Create tailored Autopilot blueprints that resolve the detected friction.", tool: "generate_solutions" },
      { step: 3, title: "Display in Command Feed", description: "Render actionable cards in Autopilot Command Center.", tool: "render_feed" },
    ],
    defaultSchedule: "Continuous live evaluation",
    defaultTrigger: "continuous",
    assignmentSupported: false,
    defaultAssignmentStrategy: "direct",
    targetType: "general",
  },
];

export function getCapabilityById(id: string): CapabilityDefinition | undefined {
  return CAPABILITIES_CATALOG.find((c) => c.id === id);
}

export function getCapabilitiesByCategory(category: CapabilityCategory): CapabilityDefinition[] {
  return CAPABILITIES_CATALOG.filter((c) => c.category === category);
}

export function getCapabilitiesByStatus(status: CapabilityStatus): CapabilityDefinition[] {
  return CAPABILITIES_CATALOG.filter((c) => c.status === status);
}
