/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as HelpRouteImport } from './routes/help'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAccountingRouteImport } from './routes/_authenticated/accounting'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedAutopilotRouteImport } from './routes/_authenticated/autopilot'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedDiscussRouteImport } from './routes/_authenticated/discuss'
import { Route as AuthenticatedHelpdeskRouteImport } from './routes/_authenticated/helpdesk'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedManufacturingRouteImport } from './routes/_authenticated/manufacturing'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedPricelistsRouteImport } from './routes/_authenticated/pricelists'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPurchaseRouteImport } from './routes/_authenticated/purchase'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as JoinTokenRouteImport } from './routes/join/$token'
import { Route as RegisterTokenRouteImport } from './routes/register/$token'
import { Route as AuthenticatedWorkflowsIndexRouteImport } from './routes/_authenticated/workflows/index'
import { Route as AuthenticatedWorkflowsWorkflowIdRouteImport } from './routes/_authenticated/workflows/$workflowId'
import { Route as AuthenticatedWorkflowsNewRouteImport } from './routes/_authenticated/workflows/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountingRoute = AuthenticatedAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutopilotRoute = AuthenticatedAutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscussRoute = AuthenticatedDiscussRouteImport.update({
  id: '/discuss',
  path: '/discuss',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpdeskRoute = AuthenticatedHelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManufacturingRoute =
  AuthenticatedManufacturingRouteImport.update({
    id: '/manufacturing',
    path: '/manufacturing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricelistsRoute = AuthenticatedPricelistsRouteImport.update({
  id: '/pricelists',
  path: '/pricelists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchaseRoute = AuthenticatedPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTokenRoute = RegisterTokenRouteImport.update({
  id: '/register/$token',
  path: '/register/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkflowsIndexRoute =
  AuthenticatedWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkflowsWorkflowIdRoute =
  AuthenticatedWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkflowsNewRoute =
  AuthenticatedWorkflowsNewRouteImport.update({
    id: '/workflows/new',
    path: '/workflows/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/callback': typeof CallbackRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/accounting': typeof AuthenticatedAccountingRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/ai': typeof AuthenticatedAiRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/autopilot': typeof AuthenticatedAutopilotRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/discuss': typeof AuthenticatedDiscussRoute
  '/helpdesk': typeof AuthenticatedHelpdeskRoute
  '/hr': typeof AuthenticatedHrRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/manufacturing': typeof AuthenticatedManufacturingRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pricelists': typeof AuthenticatedPricelistsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/purchase': typeof AuthenticatedPurchaseRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$token': typeof JoinTokenRoute
  '/register/$token': typeof RegisterTokenRoute
  '/workflows/$workflowId': typeof AuthenticatedWorkflowsWorkflowIdRoute
  '/workflows/new': typeof AuthenticatedWorkflowsNewRoute
  '/workflows/': typeof AuthenticatedWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/callback': typeof CallbackRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/accounting': typeof AuthenticatedAccountingRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/ai': typeof AuthenticatedAiRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/autopilot': typeof AuthenticatedAutopilotRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/discuss': typeof AuthenticatedDiscussRoute
  '/helpdesk': typeof AuthenticatedHelpdeskRoute
  '/hr': typeof AuthenticatedHrRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/manufacturing': typeof AuthenticatedManufacturingRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/pricelists': typeof AuthenticatedPricelistsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/purchase': typeof AuthenticatedPurchaseRoute
  '/quotations': typeof AuthenticatedQuotationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$token': typeof JoinTokenRoute
  '/register/$token': typeof RegisterTokenRoute
  '/workflows/$workflowId': typeof AuthenticatedWorkflowsWorkflowIdRoute
  '/workflows/new': typeof AuthenticatedWorkflowsNewRoute
  '/workflows': typeof AuthenticatedWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/callback': typeof CallbackRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/help': typeof HelpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/_authenticated/accounting': typeof AuthenticatedAccountingRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/autopilot': typeof AuthenticatedAutopilotRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deals': typeof AuthenticatedDealsRoute
  '/_authenticated/discuss': typeof AuthenticatedDiscussRoute
  '/_authenticated/helpdesk': typeof AuthenticatedHelpdeskRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/manufacturing': typeof AuthenticatedManufacturingRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/pricelists': typeof AuthenticatedPricelistsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/purchase': typeof AuthenticatedPurchaseRoute
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/join/$token': typeof JoinTokenRoute
  '/register/$token': typeof RegisterTokenRoute
  '/_authenticated/workflows/$workflowId': typeof AuthenticatedWorkflowsWorkflowIdRoute
  '/_authenticated/workflows/new': typeof AuthenticatedWorkflowsNewRoute
  '/_authenticated/workflows/': typeof AuthenticatedWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/callback'
    | '/careers'
    | '/contact'
    | '/docs'
    | '/help'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/templates'
    | '/terms'
    | '/accounting'
    | '/activities'
    | '/ai'
    | '/analytics'
    | '/audit-logs'
    | '/autopilot'
    | '/companies'
    | '/contacts'
    | '/crm'
    | '/customers'
    | '/dashboard'
    | '/deals'
    | '/discuss'
    | '/helpdesk'
    | '/hr'
    | '/integrations'
    | '/inventory'
    | '/invoices'
    | '/knowledge'
    | '/leads'
    | '/manufacturing'
    | '/marketing'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/pricelists'
    | '/projects'
    | '/purchase'
    | '/quotations'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/auth/callback'
    | '/join/$token'
    | '/register/$token'
    | '/workflows/$workflowId'
    | '/workflows/new'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/callback'
    | '/careers'
    | '/contact'
    | '/docs'
    | '/help'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/templates'
    | '/terms'
    | '/accounting'
    | '/activities'
    | '/ai'
    | '/analytics'
    | '/audit-logs'
    | '/autopilot'
    | '/companies'
    | '/contacts'
    | '/crm'
    | '/customers'
    | '/dashboard'
    | '/deals'
    | '/discuss'
    | '/helpdesk'
    | '/hr'
    | '/integrations'
    | '/inventory'
    | '/invoices'
    | '/knowledge'
    | '/leads'
    | '/manufacturing'
    | '/marketing'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/pricelists'
    | '/projects'
    | '/purchase'
    | '/quotations'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/auth/callback'
    | '/join/$token'
    | '/register/$token'
    | '/workflows/$workflowId'
    | '/workflows/new'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/callback'
    | '/careers'
    | '/contact'
    | '/docs'
    | '/help'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/templates'
    | '/terms'
    | '/_authenticated/accounting'
    | '/_authenticated/activities'
    | '/_authenticated/ai'
    | '/_authenticated/analytics'
    | '/_authenticated/audit-logs'
    | '/_authenticated/autopilot'
    | '/_authenticated/companies'
    | '/_authenticated/contacts'
    | '/_authenticated/crm'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/deals'
    | '/_authenticated/discuss'
    | '/_authenticated/helpdesk'
    | '/_authenticated/hr'
    | '/_authenticated/integrations'
    | '/_authenticated/inventory'
    | '/_authenticated/invoices'
    | '/_authenticated/knowledge'
    | '/_authenticated/leads'
    | '/_authenticated/manufacturing'
    | '/_authenticated/marketing'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/orders'
    | '/_authenticated/pricelists'
    | '/_authenticated/projects'
    | '/_authenticated/purchase'
    | '/_authenticated/quotations'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/team'
    | '/auth/callback'
    | '/join/$token'
    | '/register/$token'
    | '/_authenticated/workflows/$workflowId'
    | '/_authenticated/workflows/new'
    | '/_authenticated/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRoute
  CallbackRoute: typeof CallbackRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  HelpRoute: typeof HelpRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  JoinTokenRoute: typeof JoinTokenRoute
  RegisterTokenRoute: typeof RegisterTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounting': {
      id: '/_authenticated/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAccountingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/autopilot': {
      id: '/_authenticated/autopilot'
      path: '/autopilot'
      fullPath: '/autopilot'
      preLoaderRoute: typeof AuthenticatedAutopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discuss': {
      id: '/_authenticated/discuss'
      path: '/discuss'
      fullPath: '/discuss'
      preLoaderRoute: typeof AuthenticatedDiscussRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/helpdesk': {
      id: '/_authenticated/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof AuthenticatedHelpdeskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manufacturing': {
      id: '/_authenticated/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof AuthenticatedManufacturingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricelists': {
      id: '/_authenticated/pricelists'
      path: '/pricelists'
      fullPath: '/pricelists'
      preLoaderRoute: typeof AuthenticatedPricelistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase': {
      id: '/_authenticated/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof AuthenticatedPurchaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$token': {
      id: '/register/$token'
      path: '/register/$token'
      fullPath: '/register/$token'
      preLoaderRoute: typeof RegisterTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workflows/': {
      id: '/_authenticated/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthenticatedWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflows/$workflowId': {
      id: '/_authenticated/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AuthenticatedWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflows/new': {
      id: '/_authenticated/workflows/new'
      path: '/workflows/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof AuthenticatedWorkflowsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountingRoute: typeof AuthenticatedAccountingRoute
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedAutopilotRoute: typeof AuthenticatedAutopilotRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRoute
  AuthenticatedDiscussRoute: typeof AuthenticatedDiscussRoute
  AuthenticatedHelpdeskRoute: typeof AuthenticatedHelpdeskRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedManufacturingRoute: typeof AuthenticatedManufacturingRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPricelistsRoute: typeof AuthenticatedPricelistsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedPurchaseRoute: typeof AuthenticatedPurchaseRoute
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedWorkflowsWorkflowIdRoute: typeof AuthenticatedWorkflowsWorkflowIdRoute
  AuthenticatedWorkflowsNewRoute: typeof AuthenticatedWorkflowsNewRoute
  AuthenticatedWorkflowsIndexRoute: typeof AuthenticatedWorkflowsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountingRoute: AuthenticatedAccountingRoute,
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedAutopilotRoute: AuthenticatedAutopilotRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDealsRoute: AuthenticatedDealsRoute,
  AuthenticatedDiscussRoute: AuthenticatedDiscussRoute,
  AuthenticatedHelpdeskRoute: AuthenticatedHelpdeskRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedManufacturingRoute: AuthenticatedManufacturingRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPricelistsRoute: AuthenticatedPricelistsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedPurchaseRoute: AuthenticatedPurchaseRoute,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedWorkflowsWorkflowIdRoute: AuthenticatedWorkflowsWorkflowIdRoute,
  AuthenticatedWorkflowsNewRoute: AuthenticatedWorkflowsNewRoute,
  AuthenticatedWorkflowsIndexRoute: AuthenticatedWorkflowsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRoute,
  CallbackRoute: CallbackRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  HelpRoute: HelpRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  JoinTokenRoute: JoinTokenRoute,
  RegisterTokenRoute: RegisterTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
